#!/usr/bin/python

import argparse
import os
import shutil
import urllib2
import json
import sys
import subprocess

class Loaf:
    def __init__(self):
        # Check that the bin path is on the PATH
        found_on_path = False
        paths = os.environ.get('PATH').split(':')
        for path in paths:
            path = os.path.expanduser(path)
            if path == self._getBinPath():
                found_on_path = True
                break
        
        if not found_on_path:
            self._writeWarning("The executable directory (%s) is not your PATH" % self._getBinPath())
        
        # Check that our bin path is writable
        if not os.access(self._getBinPath(), os.W_OK):
            self._writeWarning("The executable directory (%s) is not writable" % self._getBinPath())
        
        # Check that the kitchen is writable
        if not os.access(self._getKitchenPath(), os.W_OK):
            self._writeWarning("The kitchen directory (%s) is not writable" % self._getKitchenPath())
        
    def install(self, package):
        # Is the package already installed?
        if self._isPackageInstalled(package):
            self._writeError("Package '%s' is already installed" % package)
            self._exit(1)
        
        self._writeNotice("Attempting to install %s.." % package)
        
        # Find repository URL
        fridge_record = self._getFridgeResponse(package)
        repository_url = fridge_record['repository']
        
        # Clone the repository to the kitchen
        subprocess.call(['git', 'clone', repository_url, package], cwd=self._getKitchenPath())
        
        # Set up the soft-link
        src = self._getPackagePath(package) + '/' + package
        dest = self._getBinPath() + '/' + package

        fnull = open(os.devnull, 'w')
        status = subprocess.call(['ln', '-s', src, dest], stderr=fnull)
        fnull.close()
        
        if status != 0:
            self._writeError("There was an error creating the soft-link at %s" % dest)
        
        self._writeSuccess("Package '" + package + "' installed successfully")
        
    def update(self, package):
        self._writeNotice("Attempting to update %s.." % package)
        
        # Check if the package exists
        if not self._isPackageInstalled(package):
            self._writeError("Package '" + package + "' is not installed")
            self._exit(2)
            
        # Pull from the remote
        subprocess.call(['git', 'pull', 'origin', 'master'], cwd=self._getPackagePath(package))
        
        self._writeSuccess("Package '%s' updated successfully" % package)
        
    def updateAll(self):
        # Updated packages
        updated_packages = []
        
        # Get a response from the fridge server
        packages = self._getFridgeResponse()

        for key in packages.keys():
            if self._isPackageInstalled(key):
                updated_packages.append(key)
                self.update(key)
        
        self._writeSuccess("Updated the following packages: %s" % ', '.join(updated_packages))

    def remove(self, package):
        self._writeNotice("Attempting to remove %s.." % package)
        
        # Check if the package exists
        if not self._isPackageInstalled(package):
            self._writeError("Package '%s' is not installed" % package)
            self._exit(2)
            
        try:
            # Remove the soft-link
            os.remove(self._getBinPath() + '/' + package)
        except OSError:
            self._writeError("Unable to delete the soft-link at %s" % self._getBinPath() + '/' + package)
        
        # Remove the actual files
        shutil.rmtree(self._getPackagePath(package))
        
        self._writeSuccess("Package '%s' removed successfully" % package)
        
    def list(self):
        # Get a response from the fridge server
        packages = self._getFridgeResponse()
        
        self._writeNotice("The following scripts are listed in the fridge:")
        
        # Print out a simple listing
        for key in packages.keys():
            if self._isPackageInstalled(key):
                colour = 92 # Green
                note = "installed"
            else:
                colour = 33 # Yellow
                note = "not installed"
            
            print("- \033[%dm%s: (%s) %s\033[0m" % (colour, key, note, packages[key]['repository']))
            print("  %s" % packages[key]['description'])
        
    def _getFridgeUrl(self):
        return 'https://secure.meanbee.com/fridge'
        
    def _getKitchenPath(self):
        path = '/usr/local/Kitchen'
        
        if not os.path.isdir(path):
            # It doesn't, lets make it
            os.makedirs(path)
        
        return path
        
    def _getBinPath(self):
        return os.path.expanduser('~/bin')
        
    def _getPackagePath(self, package):
        return self._getKitchenPath() + '/' + package
        
    def _getFridgeResponse(self, package=None):
        url = self._getFridgeUrl()

        if package:
           url += '?' + package 
           
        result_raw = urllib2.urlopen(url).read()
        result = json.loads(result_raw)
        
        if result['status'] != "OK":
            self._writeError(result['content'])
            self._exit(4)
        
        return result['content']
        
    def _isPackageInstalled(self, package):
        return os.path.isdir(self._getKitchenPath() + '/' + package)
        
    def _exit(self, code):
        sys.exit(code)
                
    def _writeError(self, message):
        sys.stderr.write('\033[91m' + '[bake] Error: ' + message + '\033[0m' + '\n')
        
    def _writeSuccess(self, message):
        sys.stderr.write('\033[92m' + '[bake] Success: ' + message + '\033[0m' + '\n')

    def _writeWarning(self, message):
        sys.stderr.write('\033[36m' + '[bake] Warning: ' + message + '\033[0m' + '\n')
        
    def _writeNotice(self, message):
        sys.stderr.write('\033[33m' + '[bake] ' + message + '\033[0m' + '\n')

parser = argparse.ArgumentParser()

subparsers = parser.add_subparsers(dest='operation')

install_parser = subparsers.add_parser('install', help='Install a script')
install_parser.add_argument('package', action='store', help='The package shortname')

remove_parser = subparsers.add_parser('remove', help='Remove a script')
remove_parser.add_argument('package', action='store', help='The package shortname')

update_parser = subparsers.add_parser('update', help='Update a script')
update_parser.add_argument('package', action='store', help='The package shortname')

updateAll_parse = subparsers.add_parser('update-all', help='Update all installed scripts')

list_parser = subparsers.add_parser('list', help='List all available scripts')

args = parser.parse_args()
op = args.operation

loaf = Loaf()

if op == 'install':
    package = args.package
    loaf.install(package)
elif op == 'remove':
    package = args.package
    loaf.remove(package)
elif op == 'update':
    package = args.package
    loaf.update(package)
elif op == 'update-all':
    loaf.updateAll()
elif op == 'list':
    loaf.list()
else:
    # argparse should prevent anyone getting here.
    sys.stderr.write("Unrecognised operation")
    sys.exit(1)

